/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio7;

/**
 *
 * @author HP
 */
public class FrmZoo extends javax.swing.JFrame {
   private static final java.util.logging.Logger logger =
    java.util.logging.Logger.getLogger(FrmZoo.class.getName());

    java.util.ArrayList<Mamifero> animales =
    new java.util.ArrayList<>();
    /**
     * Creates new form FrmZoo
     */
  public FrmZoo() {

    initComponents();

    // COLUMNAS

    javax.swing.table.DefaultTableModel modelo =
    (javax.swing.table.DefaultTableModel) tblAnimales.getModel();

    modelo.setColumnCount(0);

    modelo.addColumn("Animal");
    modelo.addColumn("Habitat");
    modelo.addColumn("Nombre Cientifico");
    modelo.addColumn("Comer");
    modelo.addColumn("Dormir");
    modelo.addColumn("Correr");
    modelo.addColumn("Comunicarse");

    // OBJETOS

    animales.add(new Leon(
            "Sabana",
            1.2,
            2.5,
            190,
            "Panthera Leo",
            8,
            80,
            15,
            114));

    animales.add(new Tigre(
            "Selva",
            1.1,
            2.8,
            220,
            "Panthera Tigris",
            9,
            70,
            "Bengala"));

    animales.add(new Guepardo(
            "Sabana",
            0.9,
            1.8,
            72,
            "Acinonyx Jubatus",
            6,
            120));

    animales.add(new Lobo(
            "Bosque",
            0.8,
            1.6,
            60,
            "Canis Lupus",
            "Gris",
            5,
            4,
            "Artico"));

    animales.add(new Perro(
            "Africa",
            0.7,
            1.4,
            30,
            "Lycaon Pictus",
            "Marron",
            4,
            300));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimales = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        tblAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAnimales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnMostrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnMostrar)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
       javax.swing.table.DefaultTableModel modelo =
      (javax.swing.table.DefaultTableModel) tblAnimales.getModel();

      modelo.setRowCount(0);

        for(Mamifero m : animales){

            modelo.addRow(new Object[]{

               m.getClass().getSimpleName(),
               m.getHabitat(),
               m.getNombreCientifico(),
               m.comer(),
               m.dormir(),
               m.correr(),
               m.comunicarse()
           });
       }

    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmZoo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnimales;
    // End of variables declaration//GEN-END:variables
}
